# Generated by Django 3.2.9 on 2021-12-18 04:29

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211218_0024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user__username']},
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.custom_upload_to),
        ),
        migrations.DeleteModel(
            name='Profiles',
        ),
    ]
