# Generated by Django 4.0 on 2022-01-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211218_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='description',
            field=models.CharField(max_length=35, null=True, unique=True),
        ),
    ]
