# Generated by Django 4.0 on 2022-01-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_entries_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='title',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
