# Generated by Django 4.0 on 2022-01-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_entries_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='download',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='entries',
            name='requirements',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='entries',
            name='screen',
            field=models.TextField(null=True, unique=True),
        ),
    ]
