# Generated by Django 4.0 on 2022-01-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_entries_download_entries_requirements_entries_screen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entries',
            old_name='download',
            new_name='article',
        ),
        migrations.RemoveField(
            model_name='entries',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='entries',
            name='screen',
        ),
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.CharField(max_length=35, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='game',
            name='download',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='game',
            name='requirements',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='game',
            name='screen',
            field=models.TextField(null=True, unique=True),
        ),
    ]
