# Generated by Django 4.0 on 2022-01-18 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_entries_funds'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entries',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='entries',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
