# Generated by Django 4.0 on 2022-01-18 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_entries_options_entries_created_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entries',
            options={},
        ),
        migrations.RemoveField(
            model_name='entries',
            name='created_on',
        ),
    ]
