# Generated by Django 4.0 on 2022-03-19 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_entries_options_remove_entries_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='screen',
        ),
        migrations.AddField(
            model_name='game',
            name='screen1',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='game',
            name='screen2',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='game',
            name='screen3',
            field=models.URLField(blank=True),
        ),
    ]
