# Generated by Django 4.0 on 2022-03-20 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_game_screen_game_screen1_game_screen2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='download',
        ),
        migrations.AddField(
            model_name='game',
            name='download1',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='game',
            name='download2',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='game',
            name='download3',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
    ]
