# Generated by Django 4.0 on 2022-03-20 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_game_download1_alter_game_download2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='requirements',
        ),
        migrations.AddField(
            model_name='game',
            name='requirement',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
