# Generated by Django 4.0 on 2022-03-20 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_game_requirements_game_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='requirementm',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='game',
            name='requirementr',
            field=models.TextField(null=True, unique=True),
        ),
    ]
