# Generated by Django 4.0.1 on 2022-03-20 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_game_requirementm_game_requirementr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aside',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top', models.CharField(max_length=30, unique=True)),
                ('bot', models.TextField(unique=True)),
                ('img', models.ImageField(upload_to='app.images')),
                ('urll', models.URLField(blank=True)),
            ],
        ),
    ]
